sudo: required
services:
  - docker

before_install: 
  - docker build -f Dockerfile.test -t kwangduck/docker-react-travis . 

script:
  - docker run -e CI=true kwangduck/docker-react-travis npm run test

language: generic
