version: '3'
services: 
  dev:
    container_name: dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - "3000:3000"
    command: ["npm", "run", "start"]
  test:
    container_name: test
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
